### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::getFallbackLocale()

### ISSUE THREAD

**Issue by sasanbabai** [laraplus/translatable#1]
Thank you for making the great extension. I searched a lot around the problem but unfortunately I could not find anything. so I decided to submit a new issue. I followed the instructions to perform installation of the package. I also tried to customize the name of the translations' table in config\translatable.php. I get this error:

FatalThrowableError in C:\Users\Administrator\Documents\Projects\afaghtadbir\vendor\laraplus\translatable\src\TranslatableServiceProvider.php line 27: Call to undefined method Illuminate\Foundation\Application::getFallbackLocale()

you'll find attached the composer.json, config\translateble.php, ProductCategoryController.php (this is the controller where I used Eloquent to query ProductCategory in the Index method) and the stack-trace.
[attachment.zip](https://github.com/laraplus/translatable/files/351492/attachment.zip)

**Comment by acasar** [comment]
Thanks for reporting. Should be fixed in 1.0.8.

If you experience any other problems feel free to open another issue.
