### ISSUE TITLE
groupBy doesnt work

### ISSUE THREAD

**Issue by Levgenij** [laraplus/translatable#13]
Item::groupBy('slug')->get() returns an error 
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'base.items.id' which is not functionally dependent on columns in GROUP BY clause;

None translantable models are working

**Comment by acasar** [comment]
@Levgenij Judging by the error message I assume that the problem is actually in the incorrect usage of groupBy. 

You can read more here: https://laracasts.com/discuss/channels/laravel/laravels-groupby-not-working
