### ISSUE TITLE
Call to a member function translatableAttributes() on null

### ISSUE THREAD

**Issue by imbrish** [laraplus/translatable#2]
Hello!

Thanks for developing the package. I really enjoy using it and just love the way it deals with translations without cluttering my app with additional models. I have to praise the documentation as well - it's comprehensive, yet very clear and concise. To sum up, great effort!

Unfortunately I stumbled upon a problem. 
I have `Amenity` model that uses `Translatable` trait. When I try to sync its many-to-many relationship
```php
$facility->amenities()->sync($request->amenity);
```
Something goes wrong and following error occurs

>
FatalErrorException in QueryBuilder.php line 106:
Call to a member function translatableAttributes() on null
1. in QueryBuilder.php line 106
2. at FatalErrorException->__construct() in HandleExceptions.php line 133
3. at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 118
4. at HandleExceptions->handleShutdown() in HandleExceptions.php line 0
5. at QueryBuilder->where() in BelongsToMany.php line 1139
6. at BelongsToMany->newPivotQuery() in BelongsToMany.php line 811
7. at BelongsToMany->sync() in FacilityController.php line 153
...

Let me know if there is something more you need to know, or if I can help in any other way.

**Comment by acasar** [comment]
Thanks for reporting. Glad you like the package!

This issue should be fixed in 1.0.9. If you still have problems let me know.
