### ISSUE TITLE
Add configuration options for fallback_locale

### ISSUE THREAD

**Issue by j6s** [laraplus/translatable#20]
It would be nice to have configuration options for fallback_locale if you want to use a fallback locale that differs from the page locale.

Ideally the library would respect strings passed to the `translatable.defaults.with_fallback` option.
In this scenario `'with_fallback' => true` would fallback to the current `app.locale`, `'with_fallback' => 'de'` would fallback to german and `'with_fallback' => false` would disable fallback.

**Comment by acasar** [comment]
@j6s Laravel already has a config option for fallback_locale: https://github.com/laravel/laravel/blob/master/config/app.php#L93

So currently we use that one. Do you have any use case where this is a problem?

**Comment by j6s** [comment]
We have an application where the record language is independent from the application locale for editors: The editor logs into the backend and is able to edit records in say french, while the rest of the page (language labels, date formats, ...) are still in his chosen locale (german for example).

I suspect that this is a very common use case, so having an option for it would make sense.

Screenshot of the actual application to clear up confusion about the use case:
![screen shot 2017-05-17 at 10 09 03 am](https://cloud.githubusercontent.com/assets/3374170/26144391/f1bb3304-3ae8-11e7-9b76-9fbfc1a18bae.png)

**Comment by acasar** [comment]
Documented here: https://github.com/laraplus/translatable#configuration-outside-laravel
