### ISSUE TITLE
::has doesnt works with nested relation

### ISSUE THREAD

**Issue by Levgenij** [laraplus/translatable#23]
class Field extends Model{
    public function children()
    {
        return $this->has(Field::class, 'parent_id');
    }
}

//
`Field::has('children')->get() returns an error Undefined index: laravel_reserved_0`

If I dont use the Translatable trait - its works with generated name "laravel_reserved_0":
`"select * from `fields` where exists (select * from `fields` as `laravel_reserved_0` where `fields`.`id` = `laravel_reserved_0`.`parent_id`)"`

**Comment by acasar** [comment]
Fixed
