### ISSUE TITLE
Force deleting does not always delete

### ISSUE THREAD

**Issue by j6s** [laraplus/translatable#29]
I came across this issue while testing some behaviour. I doubt it will come up in actual use, but it is still worth investigating to save other developers the multi-hour debugging session I just went through:

When calling `forceDelete` on a model that does not have any translations associated with it (for whatever reason) the original database row will never be deleted. This is due to the `forceDelete` method in `Builder` being defined as follows:

```
    public function forceDelete()
    {
        return $this->i18nDeleteQuery(false)->delete() && $this->query->delete();
    }
```

where  `$this->i18nDeleteQuery(false)->delete()` returns the number of deleted translation records. If there are no translation records in the `*_i18n` table then `0` is returned which is falsy - thus the second part is not executed.

---

Sidenote: I am opening the issue here since the `spletna-postaja` repository does not have issues enabled (yet?).

**Comment by acasar** [comment]
Fixed in https://github.com/spletna-postaja/translatable
