### ISSUE TITLE
Translations won't save if they're the same for many languages

### ISSUE THREAD

**Issue by imbrish** [laraplus/translatable#5]
Best explained with an example

```php
Sport::create(['picture' => 'basket.png'], [
    'en' => ['name' => 'Basketball'],
    'no' => ['name' => 'Basketball'],
]);
```

Which will only save English translation. I guess that's because Eloquent won't attempt to save model if attributes haven't changed. 

Maybe overriding `getDirty` method to check against locale/value pairs instead of just value would solve this issue?

**Comment by acasar** [comment]
Nice catch! Should be fixed in 1.0.12.
