### ISSUE TITLE
Query error on delete

### ISSUE THREAD

**Issue by Levgenij** [laraplus/translatable#6]
Laravel 5.3

ItemFilter::where('item_id', $id)->delete() 
gives me an error 

SQLSTATE[HY000]: General error: 1093 Table 'item_filters_translations' is specified twice, both as a target for 'DELETE' and as a separate source for data (SQL: delete from `item_filters_translations` where `item_filter_id` in (select `item_filters`.`id` from `item_filters` left join `item_filters_translations` on `item_filters_translations`.`item_filter_id` = `item_filters`.`id` and `item_filters_translations`.`locale` = ru where `item_id` < 13))

**Comment by Levgenij** [comment]
Worked after reinstall

**Comment by acasar** [comment]
Fixed in 1.0.13.

The problem you had before you edited the issue was probably just cache. You need to clear the cache every time your schema changes or be explicit about which attributes are translatable ($translatable property on a model).
