### ISSUE TITLE
$item->decrement('stock') returns query error

### ISSUE THREAD

**Issue by Levgenij** [laraplus/translatable#7]
$item->decrement('stock');

SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '' (SQL: update `items` left join `items_translations` on `items_translations`.`item_id` = `items`.`id` and `items_translations`.`locale` = 2016-10-31 03:57:02 set `stock` = `stock` - 1, `updated_at` = ua where `id` = 20)

**Comment by acasar** [comment]
Thanks for reporting.

Seems like Laravel has some problems with bindings when there are joins in the update statement. I had to override increment/decrement methods to solve this. Please test in 1.0.13.
