### ISSUE TITLE
Duplicate entry error in saveTranslation()

### ISSUE THREAD

**Issue by Levgenij** [laraplus/translatable#8]
**Code:**
$item->saveTranslation('ua',$data);

**Error:**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '18-en' for key 'items_translations_item_id_locale_unique' (SQL: update `items_translations` set `locale` = en, `slug` = dfgdfgg, `title` = 22222222111, `meta_title` = fdgdfg, `description` = , `meta_description` = fgfdg, `content` = where `item_id` = 18 and `locale` = ua)
[Error Screenshot](http://prntscr.com/d1gakr)

But its works if there is
$item->translateInto('ua')->first()->saveTranslation('ua',$data);

Thanks for fast responding! Your package is awesome.

**Comment by acasar** [comment]
@Levgenij Thanks for reporting! This should be fixed in 1.0.14.
